name: Build and publish release Docker image to Github Container Registry ghcr.io

on: workflow_dispatch

jobs:
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@docker-multi-platform # FIXME: replace to mani after check
    with:
      build-target: 'Docker'
      docker-multi-platform: true
      devRelease: false
      createTag: true
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}
      cisa-domain: ${{ secrets.CISA_DOMAIN }}
      cisa-user: ${{ secrets.CISA_USER }}
      cisa-password: ${{ secrets.CISA_PWD }}